plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}


version = System.getenv("CELESTIAL_VERSION") ?: new File(".release-info/1.18/VERSION").text.trim()
group = 'com.shim.celestialexploration' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
base {
    archivesName = "celestialexploration-${project.target_mc_version}"
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: 'official', version: "${project.target_mc_version}"

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run/client')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'celestialexploration'

            arg "-mixin.config=celestialexploration.mixins.json"
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                celestialexploration {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run/server')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'celestialexploration'

            arg "-mixin.config=celestialexploration.mixins.json"
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                celestialexploration {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            workingDirectory project.file('run/test')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'celestialexploration'

            arg "-mixin.config=celestialexploration.mixins.json"
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                celestialexploration {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run/data')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            args '--mod', 'celestialexploration', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            arg "-mixin.config=celestialexploration.mixins.json"
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                celestialexploration {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so:
    // flatDir {
    //     dir 'libs'
    // }

    // AzureLib maven
    maven {
        name = "AzureLib maven"
        url = "https://maven.azuredoom.com/mods"
    }

    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven { url 'https://maven.blamejared.com' }

}

dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"

    //AzureLib
    implementation fg.deobf("mod.azure.azurelib:azurelib-forge-${mc_version}:${azurelib_version}")

    // Apply Mixin AP
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // compile against the JEI API but do not include it at runtime
    compileOnly fg.deobf("mezz.jei:jei-${mc_version}:${jei_version}:api")
    // at runtime, use the full JEI jar
    runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}:${jei_version}")

    compileOnly fg.deobf("vazkii.patchouli:Patchouli:${ptch_version}:api")
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:${ptch_version}")

}

mixin {
    add sourceSets.main, "celestialexploration.mixin-refmap.json"
    config "celestialexploration.mixins.json"
}

// Example for how to get properties into the manifest for reading at runtime.
jar {
    manifest {
        attributes([
                "Specification-Title"     : "celestialexploration",
                "Specification-Vendor"    : "shim",
                "Specification-Version"   : project.version, // We are version 0 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version,
                "Implementation-Vendor"   : "shim",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : "celestialexploration.mixins.json"
        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
// publish.dependsOn('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

publishMods {
    changelog = rootProject.file("CHANGELOG/${project.base_mc_version}/current.md").text
    file = jar.archiveFile
    type = BETA
    // TODO: REMOVE THE ABOVE IN FAVOR OF THIS, VALUES ARE ALPHA, BETA, STABLE
    //type = findProperty("curseforge_release_type") ?: BETA
    modLoaders.add("forge")

    curseforge {
        projectId = "$curseforge_project_id"
        // Matches the url slug: https://www.curseforge.com/minecraft/mc-mods/celestial-exploration
        projectSlug = "celestial-exploration"
        // TODO: Uncomment so you can publish
        // accessToken = System.getenv('CURSEFORGE_API_KEY')
        minecraftVersionRange {
            start = "1.18"
            end = "1.18.2"
        }
        javaVersions.add(JavaVersion.VERSION_17)
        clientRequired = true
        serverRequired = true

        requires {"azurelib"}
        optional("jei","patchouli")
    }
}

